// Code generated by protoc-gen-go. DO NOT EDIT.
// source: algorithm.proto

package basedata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Algorithm struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CratedAtTs           int64    `protobuf:"varint,3,opt,name=crated_at_ts,json=cratedAtTs,proto3" json:"crated_at_ts,omitempty"`
	UpdatedAtTs          int64    `protobuf:"varint,4,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Algorithm) Reset()         { *m = Algorithm{} }
func (m *Algorithm) String() string { return proto.CompactTextString(m) }
func (*Algorithm) ProtoMessage()    {}
func (*Algorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{0}
}

func (m *Algorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Algorithm.Unmarshal(m, b)
}
func (m *Algorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Algorithm.Marshal(b, m, deterministic)
}
func (m *Algorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Algorithm.Merge(m, src)
}
func (m *Algorithm) XXX_Size() int {
	return xxx_messageInfo_Algorithm.Size(m)
}
func (m *Algorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_Algorithm.DiscardUnknown(m)
}

var xxx_messageInfo_Algorithm proto.InternalMessageInfo

func (m *Algorithm) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Algorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Algorithm) GetCratedAtTs() int64 {
	if m != nil {
		return m.CratedAtTs
	}
	return 0
}

func (m *Algorithm) GetUpdatedAtTs() int64 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *Algorithm) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Algorithm) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CountResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{1}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetIDRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDRequest) Reset()         { *m = GetIDRequest{} }
func (m *GetIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetIDRequest) ProtoMessage()    {}
func (*GetIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{2}
}

func (m *GetIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDRequest.Unmarshal(m, b)
}
func (m *GetIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDRequest.Marshal(b, m, deterministic)
}
func (m *GetIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDRequest.Merge(m, src)
}
func (m *GetIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetIDRequest.Size(m)
}
func (m *GetIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDRequest proto.InternalMessageInfo

func (m *GetIDRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetIDResponse struct {
	Algorithm            *Algorithm `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetIDResponse) Reset()         { *m = GetIDResponse{} }
func (m *GetIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetIDResponse) ProtoMessage()    {}
func (*GetIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c381a4f1e580eed, []int{3}
}

func (m *GetIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDResponse.Unmarshal(m, b)
}
func (m *GetIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDResponse.Marshal(b, m, deterministic)
}
func (m *GetIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDResponse.Merge(m, src)
}
func (m *GetIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetIDResponse.Size(m)
}
func (m *GetIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDResponse proto.InternalMessageInfo

func (m *GetIDResponse) GetAlgorithm() *Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return nil
}

func init() {
	proto.RegisterType((*Algorithm)(nil), "basedata.Algorithm")
	proto.RegisterType((*CountResponse)(nil), "basedata.CountResponse")
	proto.RegisterType((*GetIDRequest)(nil), "basedata.GetIDRequest")
	proto.RegisterType((*GetIDResponse)(nil), "basedata.GetIDResponse")
}

func init() { proto.RegisterFile("algorithm.proto", fileDescriptor_8c381a4f1e580eed) }

var fileDescriptor_8c381a4f1e580eed = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x29, 0x50, 0xf2, 0xf5, 0x02, 0x9f, 0x66, 0x34, 0xd8, 0x60, 0x34, 0xcd, 0x24, 0x26,
	0xac, 0x86, 0x88, 0x3b, 0x77, 0xf8, 0x27, 0xc6, 0xed, 0xe8, 0x9e, 0x0c, 0xed, 0x15, 0x9b, 0x00,
	0x53, 0x3b, 0xb7, 0x26, 0xbe, 0x82, 0xaf, 0xe3, 0x0b, 0x9a, 0x4e, 0x87, 0x16, 0xdc, 0xb5, 0xe7,
	0xfe, 0xee, 0x99, 0x73, 0x0f, 0x1c, 0xa9, 0xf5, 0x4a, 0xe7, 0x29, 0xbd, 0x6f, 0x44, 0x96, 0x6b,
	0xd2, 0xec, 0xdf, 0x52, 0x19, 0x4c, 0x14, 0xa9, 0xf1, 0xf9, 0x4a, 0xeb, 0xd5, 0x1a, 0xa7, 0x56,
	0x5f, 0x16, 0x6f, 0x53, 0xdc, 0x64, 0xf4, 0x55, 0x61, 0xfc, 0xc7, 0x83, 0x60, 0xbe, 0x5b, 0x65,
	0xff, 0xa1, 0x9d, 0x26, 0xa1, 0x17, 0x79, 0x13, 0x5f, 0xb6, 0xd3, 0x84, 0x31, 0xe8, 0x6e, 0xd5,
	0x06, 0xc3, 0x76, 0xe4, 0x4d, 0x02, 0x69, 0xbf, 0x59, 0x04, 0x83, 0x38, 0x57, 0x84, 0xc9, 0x42,
	0xd1, 0x82, 0x4c, 0xd8, 0x89, 0xbc, 0x49, 0x47, 0x42, 0xa5, 0xcd, 0xe9, 0xd5, 0x30, 0x0e, 0xc3,
	0x22, 0x4b, 0xf6, 0x90, 0xae, 0x45, 0xfa, 0x4e, 0xb4, 0xcc, 0x05, 0x40, 0x9c, 0xa3, 0x63, 0x42,
	0xdf, 0xfa, 0x07, 0x4e, 0x99, 0x53, 0x39, 0x6e, 0x2c, 0xc2, 0x5e, 0x35, 0xae, 0xf7, 0xf9, 0x15,
	0x0c, 0xef, 0x75, 0xb1, 0x25, 0x89, 0x26, 0xd3, 0x5b, 0x83, 0xec, 0x14, 0xfc, 0xb8, 0x14, 0x5c,
	0xf6, 0xea, 0x87, 0x5f, 0xc2, 0xe0, 0x09, 0xe9, 0xf9, 0x41, 0xe2, 0x47, 0x81, 0x86, 0xfe, 0x9e,
	0xc7, 0xef, 0x60, 0xe8, 0xe6, 0xce, 0xe6, 0x1a, 0x82, 0xba, 0x47, 0xcb, 0xf5, 0x67, 0x27, 0x62,
	0x57, 0xa4, 0xa8, 0x7b, 0x92, 0x0d, 0x35, 0xfb, 0xf6, 0xe0, 0xb8, 0x1e, 0xbc, 0x60, 0xfe, 0x99,
	0xc6, 0xc8, 0x6e, 0xc1, 0xb7, 0xf9, 0xd8, 0x48, 0x54, 0xe5, 0x8b, 0x5d, 0xf9, 0xe2, 0xb1, 0x2c,
	0x7f, 0x7c, 0xd6, 0xb8, 0x1e, 0x1c, 0xc2, 0x5b, 0xe5, 0xae, 0x0d, 0xc5, 0x46, 0x0d, 0xb3, 0x7f,
	0xc5, 0xfe, 0xee, 0x41, 0x7a, 0xde, 0x5a, 0xf6, 0xec, 0x33, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x48, 0x39, 0x40, 0xae, 0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AlgorithmServiceClient is the client API for AlgorithmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlgorithmServiceClient interface {
	Count(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountResponse, error)
	GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error)
}

type algorithmServiceClient struct {
	cc *grpc.ClientConn
}

func NewAlgorithmServiceClient(cc *grpc.ClientConn) AlgorithmServiceClient {
	return &algorithmServiceClient{cc}
}

func (c *algorithmServiceClient) Count(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/basedata.AlgorithmService/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmServiceClient) GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error) {
	out := new(GetIDResponse)
	err := c.cc.Invoke(ctx, "/basedata.AlgorithmService/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmServiceServer is the server API for AlgorithmService service.
type AlgorithmServiceServer interface {
	Count(context.Context, *empty.Empty) (*CountResponse, error)
	GetID(context.Context, *GetIDRequest) (*GetIDResponse, error)
}

// UnimplementedAlgorithmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlgorithmServiceServer struct {
}

func (*UnimplementedAlgorithmServiceServer) Count(ctx context.Context, req *empty.Empty) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (*UnimplementedAlgorithmServiceServer) GetID(ctx context.Context, req *GetIDRequest) (*GetIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}

func RegisterAlgorithmServiceServer(s *grpc.Server, srv AlgorithmServiceServer) {
	s.RegisterService(&_AlgorithmService_serviceDesc, srv)
}

func _AlgorithmService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.AlgorithmService/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServiceServer).Count(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlgorithmService_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServiceServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.AlgorithmService/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServiceServer).GetID(ctx, req.(*GetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlgorithmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basedata.AlgorithmService",
	HandlerType: (*AlgorithmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Count",
			Handler:    _AlgorithmService_Count_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _AlgorithmService_GetID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "algorithm.proto",
}
