// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pool.proto

package basedata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressType int32

const (
	AddressType_ALL      AddressType = 0
	AddressType_COINBASE AddressType = 1
	AddressType_PAYMENT  AddressType = 2
	AddressType_TRANSIT  AddressType = 3
	AddressType_UNKNOWN  AddressType = 4
)

var AddressType_name = map[int32]string{
	0: "ALL",
	1: "COINBASE",
	2: "PAYMENT",
	3: "TRANSIT",
	4: "UNKNOWN",
}

var AddressType_value = map[string]int32{
	"ALL":      0,
	"COINBASE": 1,
	"PAYMENT":  2,
	"TRANSIT":  3,
	"UNKNOWN":  4,
}

func (x AddressType) String() string {
	return proto.EnumName(AddressType_name, int32(x))
}

func (AddressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{0}
}

type ListPoolsRequest_SortField int32

const (
	ListPoolsRequest_S_ID            ListPoolsRequest_SortField = 0
	ListPoolsRequest_S_LIST_ORDER    ListPoolsRequest_SortField = 1
	ListPoolsRequest_S_CREATED_AT_TS ListPoolsRequest_SortField = 2
	ListPoolsRequest_S_UPDATED_AT_TS ListPoolsRequest_SortField = 3
)

var ListPoolsRequest_SortField_name = map[int32]string{
	0: "S_ID",
	1: "S_LIST_ORDER",
	2: "S_CREATED_AT_TS",
	3: "S_UPDATED_AT_TS",
}

var ListPoolsRequest_SortField_value = map[string]int32{
	"S_ID":            0,
	"S_LIST_ORDER":    1,
	"S_CREATED_AT_TS": 2,
	"S_UPDATED_AT_TS": 3,
}

func (x ListPoolsRequest_SortField) String() string {
	return proto.EnumName(ListPoolsRequest_SortField_name, int32(x))
}

func (ListPoolsRequest_SortField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 0}
}

type ListPoolsRequest_SortDirection int32

const (
	ListPoolsRequest_ASC  ListPoolsRequest_SortDirection = 0
	ListPoolsRequest_DESC ListPoolsRequest_SortDirection = 1
)

var ListPoolsRequest_SortDirection_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var ListPoolsRequest_SortDirection_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x ListPoolsRequest_SortDirection) String() string {
	return proto.EnumName(ListPoolsRequest_SortDirection_name, int32(x))
}

func (ListPoolsRequest_SortDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 1}
}

type ListPoolsRequest_QueryField int32

const (
	ListPoolsRequest_Q_STATUS ListPoolsRequest_QueryField = 0
)

var ListPoolsRequest_QueryField_name = map[int32]string{
	0: "Q_STATUS",
}

var ListPoolsRequest_QueryField_value = map[string]int32{
	"Q_STATUS": 0,
}

func (x ListPoolsRequest_QueryField) String() string {
	return proto.EnumName(ListPoolsRequest_QueryField_name, int32(x))
}

func (ListPoolsRequest_QueryField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 2}
}

type ListPoolsRequest_QueryOperator int32

const (
	ListPoolsRequest_EQ  ListPoolsRequest_QueryOperator = 0
	ListPoolsRequest_NE  ListPoolsRequest_QueryOperator = 1
	ListPoolsRequest_GTE ListPoolsRequest_QueryOperator = 2
	ListPoolsRequest_LTE ListPoolsRequest_QueryOperator = 3
	ListPoolsRequest_LT  ListPoolsRequest_QueryOperator = 4
	ListPoolsRequest_GT  ListPoolsRequest_QueryOperator = 5
)

var ListPoolsRequest_QueryOperator_name = map[int32]string{
	0: "EQ",
	1: "NE",
	2: "GTE",
	3: "LTE",
	4: "LT",
	5: "GT",
}

var ListPoolsRequest_QueryOperator_value = map[string]int32{
	"EQ":  0,
	"NE":  1,
	"GTE": 2,
	"LTE": 3,
	"LT":  4,
	"GT":  5,
}

func (x ListPoolsRequest_QueryOperator) String() string {
	return proto.EnumName(ListPoolsRequest_QueryOperator_name, int32(x))
}

func (ListPoolsRequest_QueryOperator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 3}
}

type Pool struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	ListOrder            int32    `protobuf:"varint,6,opt,name=list_order,json=listOrder,proto3" json:"list_order,omitempty"`
	CreatedAtTs          int32    `protobuf:"varint,7,opt,name=created_at_ts,json=createdAtTs,proto3" json:"created_at_ts,omitempty"`
	UpdatedAtTs          int32    `protobuf:"varint,8,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{0}
}

func (m *Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pool.Unmarshal(m, b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return xxx_messageInfo_Pool.Size(m)
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pool) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

func (m *Pool) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Pool) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Pool) GetListOrder() int32 {
	if m != nil {
		return m.ListOrder
	}
	return 0
}

func (m *Pool) GetCreatedAtTs() int32 {
	if m != nil {
		return m.CreatedAtTs
	}
	return 0
}

func (m *Pool) GetUpdatedAtTs() int32 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *Pool) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Pool) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type PoolAddress struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PoolId               int32    `protobuf:"varint,3,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinId               int32    `protobuf:"varint,4,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAtTs          int32    `protobuf:"varint,6,opt,name=created_at_ts,json=createdAtTs,proto3" json:"created_at_ts,omitempty"`
	UpdatedAtTs          int32    `protobuf:"varint,7,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolAddress) Reset()         { *m = PoolAddress{} }
func (m *PoolAddress) String() string { return proto.CompactTextString(m) }
func (*PoolAddress) ProtoMessage()    {}
func (*PoolAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{1}
}

func (m *PoolAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolAddress.Unmarshal(m, b)
}
func (m *PoolAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolAddress.Marshal(b, m, deterministic)
}
func (m *PoolAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolAddress.Merge(m, src)
}
func (m *PoolAddress) XXX_Size() int {
	return xxx_messageInfo_PoolAddress.Size(m)
}
func (m *PoolAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolAddress.DiscardUnknown(m)
}

var xxx_messageInfo_PoolAddress proto.InternalMessageInfo

func (m *PoolAddress) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PoolAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PoolAddress) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *PoolAddress) GetCoinId() int32 {
	if m != nil {
		return m.CoinId
	}
	return 0
}

func (m *PoolAddress) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PoolAddress) GetCreatedAtTs() int32 {
	if m != nil {
		return m.CreatedAtTs
	}
	return 0
}

func (m *PoolAddress) GetUpdatedAtTs() int32 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *PoolAddress) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PoolAddress) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type PoolCoinbaseTag struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PoolId               int32    `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Tag                  []byte   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	CreatedAtTs          int32    `protobuf:"varint,4,opt,name=created_at_ts,json=createdAtTs,proto3" json:"created_at_ts,omitempty"`
	UpdatedAtTs          int32    `protobuf:"varint,5,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolCoinbaseTag) Reset()         { *m = PoolCoinbaseTag{} }
func (m *PoolCoinbaseTag) String() string { return proto.CompactTextString(m) }
func (*PoolCoinbaseTag) ProtoMessage()    {}
func (*PoolCoinbaseTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{2}
}

func (m *PoolCoinbaseTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolCoinbaseTag.Unmarshal(m, b)
}
func (m *PoolCoinbaseTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolCoinbaseTag.Marshal(b, m, deterministic)
}
func (m *PoolCoinbaseTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolCoinbaseTag.Merge(m, src)
}
func (m *PoolCoinbaseTag) XXX_Size() int {
	return xxx_messageInfo_PoolCoinbaseTag.Size(m)
}
func (m *PoolCoinbaseTag) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolCoinbaseTag.DiscardUnknown(m)
}

var xxx_messageInfo_PoolCoinbaseTag proto.InternalMessageInfo

func (m *PoolCoinbaseTag) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PoolCoinbaseTag) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *PoolCoinbaseTag) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *PoolCoinbaseTag) GetCreatedAtTs() int32 {
	if m != nil {
		return m.CreatedAtTs
	}
	return 0
}

func (m *PoolCoinbaseTag) GetUpdatedAtTs() int32 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *PoolCoinbaseTag) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PoolCoinbaseTag) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CountPoolsResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountPoolsResponse) Reset()         { *m = CountPoolsResponse{} }
func (m *CountPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*CountPoolsResponse) ProtoMessage()    {}
func (*CountPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{3}
}

func (m *CountPoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPoolsResponse.Unmarshal(m, b)
}
func (m *CountPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPoolsResponse.Marshal(b, m, deterministic)
}
func (m *CountPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPoolsResponse.Merge(m, src)
}
func (m *CountPoolsResponse) XXX_Size() int {
	return xxx_messageInfo_CountPoolsResponse.Size(m)
}
func (m *CountPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountPoolsResponse proto.InternalMessageInfo

func (m *CountPoolsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetPoolRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPoolRequest) Reset()         { *m = GetPoolRequest{} }
func (m *GetPoolRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolRequest) ProtoMessage()    {}
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{4}
}

func (m *GetPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolRequest.Unmarshal(m, b)
}
func (m *GetPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolRequest.Marshal(b, m, deterministic)
}
func (m *GetPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolRequest.Merge(m, src)
}
func (m *GetPoolRequest) XXX_Size() int {
	return xxx_messageInfo_GetPoolRequest.Size(m)
}
func (m *GetPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolRequest proto.InternalMessageInfo

func (m *GetPoolRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPoolResponse struct {
	Pool                 *Pool    `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPoolResponse) Reset()         { *m = GetPoolResponse{} }
func (m *GetPoolResponse) String() string { return proto.CompactTextString(m) }
func (*GetPoolResponse) ProtoMessage()    {}
func (*GetPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{5}
}

func (m *GetPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolResponse.Unmarshal(m, b)
}
func (m *GetPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolResponse.Marshal(b, m, deterministic)
}
func (m *GetPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolResponse.Merge(m, src)
}
func (m *GetPoolResponse) XXX_Size() int {
	return xxx_messageInfo_GetPoolResponse.Size(m)
}
func (m *GetPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolResponse proto.InternalMessageInfo

func (m *GetPoolResponse) GetPool() *Pool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type GetPoolAddressesRequest struct {
	PoolId               int32       `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinId               int32       `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Type                 AddressType `protobuf:"varint,3,opt,name=type,proto3,enum=basedata.AddressType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPoolAddressesRequest) Reset()         { *m = GetPoolAddressesRequest{} }
func (m *GetPoolAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolAddressesRequest) ProtoMessage()    {}
func (*GetPoolAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{6}
}

func (m *GetPoolAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolAddressesRequest.Unmarshal(m, b)
}
func (m *GetPoolAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetPoolAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolAddressesRequest.Merge(m, src)
}
func (m *GetPoolAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPoolAddressesRequest.Size(m)
}
func (m *GetPoolAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolAddressesRequest proto.InternalMessageInfo

func (m *GetPoolAddressesRequest) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *GetPoolAddressesRequest) GetCoinId() int32 {
	if m != nil {
		return m.CoinId
	}
	return 0
}

func (m *GetPoolAddressesRequest) GetType() AddressType {
	if m != nil {
		return m.Type
	}
	return AddressType_ALL
}

type GetPoolAddressesResponse struct {
	Addresses            []*PoolAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPoolAddressesResponse) Reset()         { *m = GetPoolAddressesResponse{} }
func (m *GetPoolAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPoolAddressesResponse) ProtoMessage()    {}
func (*GetPoolAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{7}
}

func (m *GetPoolAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolAddressesResponse.Unmarshal(m, b)
}
func (m *GetPoolAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetPoolAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolAddressesResponse.Merge(m, src)
}
func (m *GetPoolAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPoolAddressesResponse.Size(m)
}
func (m *GetPoolAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolAddressesResponse proto.InternalMessageInfo

func (m *GetPoolAddressesResponse) GetAddresses() []*PoolAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type GetPoolCoinbaseTagsRequest struct {
	PoolId               int32    `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPoolCoinbaseTagsRequest) Reset()         { *m = GetPoolCoinbaseTagsRequest{} }
func (m *GetPoolCoinbaseTagsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPoolCoinbaseTagsRequest) ProtoMessage()    {}
func (*GetPoolCoinbaseTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{8}
}

func (m *GetPoolCoinbaseTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolCoinbaseTagsRequest.Unmarshal(m, b)
}
func (m *GetPoolCoinbaseTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolCoinbaseTagsRequest.Marshal(b, m, deterministic)
}
func (m *GetPoolCoinbaseTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolCoinbaseTagsRequest.Merge(m, src)
}
func (m *GetPoolCoinbaseTagsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPoolCoinbaseTagsRequest.Size(m)
}
func (m *GetPoolCoinbaseTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolCoinbaseTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolCoinbaseTagsRequest proto.InternalMessageInfo

func (m *GetPoolCoinbaseTagsRequest) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

type GetPoolCoinbaseTagsResponse struct {
	Tags                 []*PoolCoinbaseTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPoolCoinbaseTagsResponse) Reset()         { *m = GetPoolCoinbaseTagsResponse{} }
func (m *GetPoolCoinbaseTagsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPoolCoinbaseTagsResponse) ProtoMessage()    {}
func (*GetPoolCoinbaseTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{9}
}

func (m *GetPoolCoinbaseTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPoolCoinbaseTagsResponse.Unmarshal(m, b)
}
func (m *GetPoolCoinbaseTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPoolCoinbaseTagsResponse.Marshal(b, m, deterministic)
}
func (m *GetPoolCoinbaseTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPoolCoinbaseTagsResponse.Merge(m, src)
}
func (m *GetPoolCoinbaseTagsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPoolCoinbaseTagsResponse.Size(m)
}
func (m *GetPoolCoinbaseTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPoolCoinbaseTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPoolCoinbaseTagsResponse proto.InternalMessageInfo

func (m *GetPoolCoinbaseTagsResponse) GetTags() []*PoolCoinbaseTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AddPoolCoinbaseAddressRequest struct {
	Address              string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PoolId               int32       `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinId               int32       `protobuf:"varint,3,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Type                 AddressType `protobuf:"varint,4,opt,name=type,proto3,enum=basedata.AddressType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddPoolCoinbaseAddressRequest) Reset()         { *m = AddPoolCoinbaseAddressRequest{} }
func (m *AddPoolCoinbaseAddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddPoolCoinbaseAddressRequest) ProtoMessage()    {}
func (*AddPoolCoinbaseAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{10}
}

func (m *AddPoolCoinbaseAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPoolCoinbaseAddressRequest.Unmarshal(m, b)
}
func (m *AddPoolCoinbaseAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPoolCoinbaseAddressRequest.Marshal(b, m, deterministic)
}
func (m *AddPoolCoinbaseAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPoolCoinbaseAddressRequest.Merge(m, src)
}
func (m *AddPoolCoinbaseAddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddPoolCoinbaseAddressRequest.Size(m)
}
func (m *AddPoolCoinbaseAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPoolCoinbaseAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPoolCoinbaseAddressRequest proto.InternalMessageInfo

func (m *AddPoolCoinbaseAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddPoolCoinbaseAddressRequest) GetPoolId() int32 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *AddPoolCoinbaseAddressRequest) GetCoinId() int32 {
	if m != nil {
		return m.CoinId
	}
	return 0
}

func (m *AddPoolCoinbaseAddressRequest) GetType() AddressType {
	if m != nil {
		return m.Type
	}
	return AddressType_ALL
}

type AddPoolCoinbaseAddressResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPoolCoinbaseAddressResponse) Reset()         { *m = AddPoolCoinbaseAddressResponse{} }
func (m *AddPoolCoinbaseAddressResponse) String() string { return proto.CompactTextString(m) }
func (*AddPoolCoinbaseAddressResponse) ProtoMessage()    {}
func (*AddPoolCoinbaseAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{11}
}

func (m *AddPoolCoinbaseAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPoolCoinbaseAddressResponse.Unmarshal(m, b)
}
func (m *AddPoolCoinbaseAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPoolCoinbaseAddressResponse.Marshal(b, m, deterministic)
}
func (m *AddPoolCoinbaseAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPoolCoinbaseAddressResponse.Merge(m, src)
}
func (m *AddPoolCoinbaseAddressResponse) XXX_Size() int {
	return xxx_messageInfo_AddPoolCoinbaseAddressResponse.Size(m)
}
func (m *AddPoolCoinbaseAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPoolCoinbaseAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPoolCoinbaseAddressResponse proto.InternalMessageInfo

func (m *AddPoolCoinbaseAddressResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type ListPoolsResponse struct {
	Pools                []*Pool  `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPoolsResponse) Reset()         { *m = ListPoolsResponse{} }
func (m *ListPoolsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPoolsResponse) ProtoMessage()    {}
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{12}
}

func (m *ListPoolsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsResponse.Unmarshal(m, b)
}
func (m *ListPoolsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsResponse.Marshal(b, m, deterministic)
}
func (m *ListPoolsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsResponse.Merge(m, src)
}
func (m *ListPoolsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPoolsResponse.Size(m)
}
func (m *ListPoolsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsResponse proto.InternalMessageInfo

func (m *ListPoolsResponse) GetPools() []*Pool {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *ListPoolsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ListPoolsRequest struct {
	Queries              []*ListPoolsRequest_Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Sorts                []*ListPoolsRequest_Sort  `protobuf:"bytes,2,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Limit                int32                     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip                 int32                     `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	OnlyTotal            bool                      `protobuf:"varint,5,opt,name=onlyTotal,proto3" json:"onlyTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListPoolsRequest) Reset()         { *m = ListPoolsRequest{} }
func (m *ListPoolsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPoolsRequest) ProtoMessage()    {}
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13}
}

func (m *ListPoolsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsRequest.Unmarshal(m, b)
}
func (m *ListPoolsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsRequest.Marshal(b, m, deterministic)
}
func (m *ListPoolsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsRequest.Merge(m, src)
}
func (m *ListPoolsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPoolsRequest.Size(m)
}
func (m *ListPoolsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsRequest proto.InternalMessageInfo

func (m *ListPoolsRequest) GetQueries() []*ListPoolsRequest_Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *ListPoolsRequest) GetSorts() []*ListPoolsRequest_Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

func (m *ListPoolsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListPoolsRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListPoolsRequest) GetOnlyTotal() bool {
	if m != nil {
		return m.OnlyTotal
	}
	return false
}

type ListPoolsRequest_Sort struct {
	Field                ListPoolsRequest_SortField     `protobuf:"varint,1,opt,name=field,proto3,enum=basedata.ListPoolsRequest_SortField" json:"field,omitempty"`
	Direction            ListPoolsRequest_SortDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=basedata.ListPoolsRequest_SortDirection" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListPoolsRequest_Sort) Reset()         { *m = ListPoolsRequest_Sort{} }
func (m *ListPoolsRequest_Sort) String() string { return proto.CompactTextString(m) }
func (*ListPoolsRequest_Sort) ProtoMessage()    {}
func (*ListPoolsRequest_Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 0}
}

func (m *ListPoolsRequest_Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsRequest_Sort.Unmarshal(m, b)
}
func (m *ListPoolsRequest_Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsRequest_Sort.Marshal(b, m, deterministic)
}
func (m *ListPoolsRequest_Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsRequest_Sort.Merge(m, src)
}
func (m *ListPoolsRequest_Sort) XXX_Size() int {
	return xxx_messageInfo_ListPoolsRequest_Sort.Size(m)
}
func (m *ListPoolsRequest_Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsRequest_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsRequest_Sort proto.InternalMessageInfo

func (m *ListPoolsRequest_Sort) GetField() ListPoolsRequest_SortField {
	if m != nil {
		return m.Field
	}
	return ListPoolsRequest_S_ID
}

func (m *ListPoolsRequest_Sort) GetDirection() ListPoolsRequest_SortDirection {
	if m != nil {
		return m.Direction
	}
	return ListPoolsRequest_ASC
}

type ListPoolsRequest_Query struct {
	Field                ListPoolsRequest_QueryField    `protobuf:"varint,1,opt,name=field,proto3,enum=basedata.ListPoolsRequest_QueryField" json:"field,omitempty"`
	Operator             ListPoolsRequest_QueryOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=basedata.ListPoolsRequest_QueryOperator" json:"operator,omitempty"`
	Value                *any.Any                       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListPoolsRequest_Query) Reset()         { *m = ListPoolsRequest_Query{} }
func (m *ListPoolsRequest_Query) String() string { return proto.CompactTextString(m) }
func (*ListPoolsRequest_Query) ProtoMessage()    {}
func (*ListPoolsRequest_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a14d8612184524f, []int{13, 1}
}

func (m *ListPoolsRequest_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPoolsRequest_Query.Unmarshal(m, b)
}
func (m *ListPoolsRequest_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPoolsRequest_Query.Marshal(b, m, deterministic)
}
func (m *ListPoolsRequest_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPoolsRequest_Query.Merge(m, src)
}
func (m *ListPoolsRequest_Query) XXX_Size() int {
	return xxx_messageInfo_ListPoolsRequest_Query.Size(m)
}
func (m *ListPoolsRequest_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPoolsRequest_Query.DiscardUnknown(m)
}

var xxx_messageInfo_ListPoolsRequest_Query proto.InternalMessageInfo

func (m *ListPoolsRequest_Query) GetField() ListPoolsRequest_QueryField {
	if m != nil {
		return m.Field
	}
	return ListPoolsRequest_Q_STATUS
}

func (m *ListPoolsRequest_Query) GetOperator() ListPoolsRequest_QueryOperator {
	if m != nil {
		return m.Operator
	}
	return ListPoolsRequest_EQ
}

func (m *ListPoolsRequest_Query) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("basedata.AddressType", AddressType_name, AddressType_value)
	proto.RegisterEnum("basedata.ListPoolsRequest_SortField", ListPoolsRequest_SortField_name, ListPoolsRequest_SortField_value)
	proto.RegisterEnum("basedata.ListPoolsRequest_SortDirection", ListPoolsRequest_SortDirection_name, ListPoolsRequest_SortDirection_value)
	proto.RegisterEnum("basedata.ListPoolsRequest_QueryField", ListPoolsRequest_QueryField_name, ListPoolsRequest_QueryField_value)
	proto.RegisterEnum("basedata.ListPoolsRequest_QueryOperator", ListPoolsRequest_QueryOperator_name, ListPoolsRequest_QueryOperator_value)
	proto.RegisterType((*Pool)(nil), "basedata.Pool")
	proto.RegisterType((*PoolAddress)(nil), "basedata.PoolAddress")
	proto.RegisterType((*PoolCoinbaseTag)(nil), "basedata.PoolCoinbaseTag")
	proto.RegisterType((*CountPoolsResponse)(nil), "basedata.CountPoolsResponse")
	proto.RegisterType((*GetPoolRequest)(nil), "basedata.GetPoolRequest")
	proto.RegisterType((*GetPoolResponse)(nil), "basedata.GetPoolResponse")
	proto.RegisterType((*GetPoolAddressesRequest)(nil), "basedata.GetPoolAddressesRequest")
	proto.RegisterType((*GetPoolAddressesResponse)(nil), "basedata.GetPoolAddressesResponse")
	proto.RegisterType((*GetPoolCoinbaseTagsRequest)(nil), "basedata.GetPoolCoinbaseTagsRequest")
	proto.RegisterType((*GetPoolCoinbaseTagsResponse)(nil), "basedata.GetPoolCoinbaseTagsResponse")
	proto.RegisterType((*AddPoolCoinbaseAddressRequest)(nil), "basedata.AddPoolCoinbaseAddressRequest")
	proto.RegisterType((*AddPoolCoinbaseAddressResponse)(nil), "basedata.AddPoolCoinbaseAddressResponse")
	proto.RegisterType((*ListPoolsResponse)(nil), "basedata.ListPoolsResponse")
	proto.RegisterType((*ListPoolsRequest)(nil), "basedata.ListPoolsRequest")
	proto.RegisterType((*ListPoolsRequest_Sort)(nil), "basedata.ListPoolsRequest.Sort")
	proto.RegisterType((*ListPoolsRequest_Query)(nil), "basedata.ListPoolsRequest.Query")
}

func init() { proto.RegisterFile("pool.proto", fileDescriptor_8a14d8612184524f) }

var fileDescriptor_8a14d8612184524f = []byte{
	// 1105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x29, 0x52, 0x3f, 0xa3, 0x58, 0x66, 0x37, 0xa9, 0x43, 0xd3, 0x71, 0xe3, 0x12, 0x0e,
	0xea, 0x1a, 0xa8, 0x02, 0x28, 0x30, 0x50, 0xa4, 0x97, 0xb2, 0x92, 0x6c, 0x08, 0x51, 0x25, 0x9b,
	0xa4, 0x51, 0x14, 0x3d, 0x10, 0xb4, 0xb8, 0x11, 0x88, 0xd2, 0xa2, 0x42, 0xae, 0x5c, 0xe8, 0xdc,
	0x5b, 0x2f, 0xbd, 0xf5, 0xd4, 0xe7, 0xe8, 0x83, 0xf4, 0x2d, 0xfa, 0x16, 0xc5, 0x2e, 0x97, 0x3f,
	0xfa, 0xb3, 0x7c, 0xe2, 0xce, 0xcc, 0x37, 0xb3, 0x33, 0x1f, 0x67, 0x67, 0x17, 0x60, 0x16, 0x86,
	0x41, 0x6b, 0x16, 0x85, 0x24, 0x44, 0xb5, 0x3b, 0x37, 0xc6, 0x9e, 0x4b, 0x5c, 0xed, 0x68, 0x12,
	0x86, 0x93, 0x00, 0xbf, 0x65, 0xfa, 0xbb, 0xf9, 0xc7, 0xb7, 0xf8, 0x7e, 0x46, 0x16, 0x09, 0x4c,
	0x3b, 0x5c, 0x35, 0xba, 0x53, 0x6e, 0xd2, 0xff, 0x16, 0x41, 0xba, 0x0e, 0xc3, 0x00, 0x35, 0x41,
	0xf4, 0x3d, 0x55, 0x38, 0x11, 0xce, 0x64, 0x53, 0xf4, 0x3d, 0x84, 0x40, 0x9a, 0xba, 0xf7, 0x58,
	0x15, 0x4f, 0x84, 0xb3, 0xba, 0xc9, 0xd6, 0xe8, 0x35, 0x34, 0x7e, 0xc3, 0x77, 0xb1, 0x4f, 0xb0,
	0x33, 0x8f, 0x02, 0xb5, 0xcc, 0x4c, 0xc0, 0x55, 0xb7, 0x51, 0x40, 0x9d, 0xfc, 0x71, 0x38, 0x55,
	0xa5, 0xc4, 0x89, 0xae, 0xd1, 0x01, 0x54, 0x62, 0xe2, 0x92, 0x79, 0xac, 0xca, 0x2c, 0x38, 0x97,
	0xd0, 0x31, 0x40, 0xe0, 0xc7, 0xc4, 0x09, 0x23, 0x0f, 0x47, 0x6a, 0x85, 0xd9, 0xea, 0x54, 0x33,
	0xa2, 0x0a, 0xa4, 0xc3, 0xde, 0x38, 0xc2, 0x2e, 0xc1, 0x9e, 0xe3, 0x12, 0x87, 0xc4, 0x6a, 0x95,
	0x21, 0x1a, 0x5c, 0x69, 0x10, 0x3b, 0xa6, 0x98, 0xf9, 0xcc, 0x2b, 0x60, 0x6a, 0x09, 0x86, 0x2b,
	0x19, 0xe6, 0x18, 0x20, 0x8f, 0xa3, 0xd6, 0x59, 0x62, 0xf5, 0x2c, 0x08, 0x35, 0xe7, 0x21, 0x54,
	0x48, 0xcc, 0x99, 0xbf, 0xfe, 0xbb, 0x08, 0x0d, 0x4a, 0x8f, 0xe1, 0x79, 0x11, 0x8e, 0xe3, 0x35,
	0x96, 0x54, 0xa8, 0xba, 0x89, 0x89, 0x13, 0x95, 0x8a, 0xe8, 0x25, 0x54, 0xe9, 0x8f, 0x72, 0x7c,
	0x8f, 0xf1, 0x24, 0x9b, 0x15, 0x2a, 0xf6, 0x3d, 0x6a, 0x18, 0x87, 0xfe, 0x94, 0x1a, 0xa4, 0xc4,
	0x40, 0xc5, 0x3e, 0x63, 0x9c, 0x2c, 0x66, 0x98, 0xd3, 0xc4, 0xd6, 0xeb, 0x2c, 0x54, 0x9e, 0xc0,
	0x42, 0x75, 0x17, 0x0b, 0xb5, 0xc7, 0x59, 0xa8, 0xaf, 0xb2, 0xf0, 0xaf, 0x00, 0xfb, 0x94, 0x85,
	0x4e, 0xe8, 0x4f, 0x69, 0xc7, 0xd9, 0xee, 0x64, 0x8d, 0x89, 0x42, 0xbd, 0xe2, 0x52, 0xbd, 0x0a,
	0x94, 0x89, 0x3b, 0x61, 0x24, 0x3c, 0x33, 0xe9, 0x72, 0xbd, 0x28, 0xe9, 0x09, 0x45, 0xc9, 0xbb,
	0x8a, 0xaa, 0x3c, 0x5e, 0x54, 0x75, 0xb5, 0xa8, 0x73, 0x40, 0x9d, 0x70, 0x3e, 0x25, 0xb4, 0xb0,
	0xd8, 0xc4, 0xf1, 0x2c, 0x9c, 0xc6, 0x18, 0xbd, 0x00, 0x79, 0x4c, 0xb5, 0xbc, 0xb2, 0x44, 0xd0,
	0x4f, 0xa0, 0x79, 0x85, 0x19, 0xd2, 0xc4, 0x9f, 0xe6, 0x38, 0x26, 0xab, 0xe5, 0xeb, 0x17, 0xb0,
	0x9f, 0x21, 0x78, 0x28, 0x1d, 0x24, 0x4a, 0x01, 0x03, 0x35, 0xda, 0xcd, 0x56, 0x7a, 0x56, 0x5b,
	0x0c, 0xc5, 0x6c, 0xfa, 0x03, 0xbc, 0xe4, 0x6e, 0xbc, 0xc3, 0x70, 0x9c, 0xee, 0x50, 0x20, 0x54,
	0xd8, 0xd6, 0x40, 0xe2, 0x52, 0x03, 0x7d, 0xcd, 0x1b, 0x88, 0x52, 0xdd, 0x6c, 0x7f, 0x9e, 0x6f,
	0xc8, 0x63, 0xdb, 0x8b, 0x19, 0x4e, 0xfa, 0x4a, 0x1f, 0x81, 0xba, 0xbe, 0x2f, 0xcf, 0xfb, 0x1d,
	0xd4, 0xdd, 0x54, 0xa9, 0x0a, 0x27, 0xe5, 0xb3, 0x46, 0x31, 0x56, 0xc1, 0xc7, 0xcc, 0x71, 0xfa,
	0x05, 0x68, 0x3c, 0x60, 0xa1, 0x49, 0x76, 0xd6, 0xa2, 0x0f, 0xe0, 0x68, 0xa3, 0x1b, 0x4f, 0xe5,
	0x1b, 0x90, 0x88, 0x3b, 0x49, 0xb3, 0x38, 0x5c, 0xce, 0xa2, 0xe0, 0x61, 0x32, 0x98, 0xfe, 0x97,
	0x00, 0xc7, 0x86, 0xe7, 0x15, 0x8d, 0x69, 0xaa, 0x3c, 0x91, 0xc2, 0x79, 0x15, 0xb6, 0x9e, 0x57,
	0x71, 0x1b, 0xdd, 0xe5, 0x8d, 0x74, 0x4b, 0xbb, 0xe9, 0xfe, 0x16, 0xbe, 0xd8, 0x96, 0x17, 0xaf,
	0xf4, 0x00, 0x2a, 0x11, 0x8e, 0xe7, 0x41, 0xd2, 0x78, 0x35, 0x93, 0x4b, 0xfa, 0x08, 0x3e, 0x1b,
	0xf8, 0xf1, 0x4a, 0x93, 0x9e, 0x82, 0x4c, 0x93, 0x4b, 0x79, 0x59, 0x6d, 0xad, 0xc4, 0x48, 0x5b,
	0x99, 0x84, 0xc4, 0x0d, 0x78, 0x3d, 0x89, 0xa0, 0xff, 0x27, 0x83, 0x52, 0x88, 0x98, 0xd0, 0xf2,
	0x1e, 0xaa, 0x9f, 0xe6, 0x38, 0xf2, 0xb3, 0x1f, 0x7e, 0x92, 0x87, 0x5c, 0x05, 0xb7, 0x6e, 0xe6,
	0x38, 0x5a, 0x98, 0xa9, 0x03, 0xba, 0x00, 0x39, 0x0e, 0x23, 0x42, 0x07, 0x20, 0xf5, 0x7c, 0xfd,
	0x88, 0xa7, 0x15, 0x46, 0xc4, 0x4c, 0xd0, 0x34, 0xbb, 0xc0, 0xbf, 0xf7, 0x09, 0x27, 0x35, 0x11,
	0xe8, 0x0c, 0x8c, 0x7f, 0xf5, 0x67, 0x7c, 0x22, 0xb0, 0x35, 0x7a, 0x05, 0xf5, 0x70, 0x1a, 0x2c,
	0x6c, 0x56, 0x8b, 0xcc, 0xd8, 0xc9, 0x15, 0xda, 0x1f, 0x02, 0x48, 0x34, 0x2e, 0x7a, 0x0f, 0xf2,
	0x47, 0x1f, 0x07, 0x49, 0x87, 0x35, 0xdb, 0xa7, 0x3b, 0xf2, 0xb8, 0xa4, 0x58, 0x33, 0x71, 0x41,
	0x97, 0x50, 0xf7, 0xfc, 0x08, 0x8f, 0x89, 0x1f, 0x4e, 0x19, 0x5d, 0xcd, 0xf6, 0xd9, 0x0e, 0xff,
	0x6e, 0x8a, 0x37, 0x73, 0x57, 0xed, 0x1f, 0x01, 0x64, 0x46, 0x0f, 0xfa, 0x6e, 0x39, 0x9b, 0x37,
	0xbb, 0xf8, 0x5c, 0x4a, 0xa7, 0x0b, 0xb5, 0x70, 0x86, 0x23, 0x97, 0x84, 0xd1, 0x13, 0xb2, 0x61,
	0xfe, 0x23, 0x8e, 0x37, 0x33, 0x4f, 0x74, 0x0e, 0xf2, 0x83, 0x1b, 0xcc, 0x93, 0x79, 0xd0, 0x68,
	0xbf, 0x68, 0x25, 0xaf, 0x80, 0x56, 0xfa, 0x0a, 0x68, 0x19, 0xd3, 0x85, 0x99, 0x40, 0xf4, 0x1b,
	0xa8, 0x67, 0xa4, 0xa0, 0x1a, 0x48, 0x96, 0xd3, 0xef, 0x2a, 0x25, 0xa4, 0xc0, 0x33, 0xcb, 0x19,
	0xf4, 0x2d, 0xdb, 0x19, 0x99, 0xdd, 0x9e, 0xa9, 0x08, 0xe8, 0x39, 0xec, 0x5b, 0x4e, 0xc7, 0xec,
	0x19, 0x76, 0xaf, 0xeb, 0x18, 0xb6, 0x63, 0x5b, 0x8a, 0x98, 0x28, 0x6f, 0xaf, 0xbb, 0x05, 0x65,
	0x59, 0xd7, 0x61, 0x6f, 0x89, 0x27, 0x54, 0x85, 0xb2, 0x61, 0x75, 0x94, 0x12, 0x8d, 0xdf, 0xed,
	0x59, 0x1d, 0x45, 0xd0, 0x35, 0x80, 0xbc, 0x7a, 0xf4, 0x0c, 0x6a, 0x37, 0x8e, 0x65, 0x1b, 0xf6,
	0xad, 0xa5, 0x94, 0x74, 0x03, 0xf6, 0x96, 0x2a, 0x43, 0x15, 0x10, 0x7b, 0x37, 0x4a, 0x89, 0x7e,
	0x87, 0x3d, 0x45, 0xa0, 0xf1, 0xae, 0xec, 0x9e, 0x22, 0xd2, 0xc5, 0xc0, 0xee, 0x29, 0x65, 0x6a,
	0x19, 0xd8, 0x8a, 0x44, 0xbf, 0x57, 0xb6, 0x22, 0x9f, 0x7f, 0x80, 0x46, 0xe1, 0x2c, 0xb2, 0x04,
	0x06, 0x03, 0xa5, 0x44, 0x37, 0xea, 0x8c, 0xfa, 0xc3, 0x1f, 0x0c, 0x8b, 0xc6, 0x69, 0x40, 0xf5,
	0xda, 0xf8, 0xf9, 0xc7, 0xde, 0xd0, 0x56, 0x44, 0x2a, 0xd8, 0xa6, 0x31, 0xb4, 0xfa, 0xb6, 0x52,
	0xa6, 0xc2, 0xed, 0xf0, 0xc3, 0x70, 0xf4, 0xd3, 0x50, 0x91, 0xda, 0x7f, 0x4a, 0xc9, 0x53, 0xc0,
	0xc2, 0xd1, 0x83, 0x3f, 0xc6, 0xa8, 0x0b, 0x90, 0xdf, 0x1f, 0xe8, 0x60, 0x8d, 0xdd, 0x1e, 0x7d,
	0x80, 0x69, 0xaf, 0xf2, 0x1f, 0xb7, 0x7e, 0xdb, 0xe8, 0x25, 0xf4, 0x3d, 0x54, 0xf9, 0x00, 0x44,
	0x6a, 0x0e, 0x5d, 0xbe, 0x6c, 0xb4, 0xc3, 0x0d, 0x96, 0x2c, 0xc2, 0x2f, 0xa0, 0xac, 0x8e, 0x72,
	0xf4, 0xe5, 0x9a, 0xc3, 0xea, 0xf5, 0xa2, 0xe9, 0x8f, 0x41, 0xb2, 0xe0, 0x1e, 0x3c, 0xdf, 0x30,
	0x9f, 0xd1, 0xe9, 0x9a, 0xf3, 0x86, 0xa9, 0xaf, 0xbd, 0xd9, 0x81, 0xca, 0x76, 0xb9, 0x87, 0x83,
	0xcd, 0xe3, 0x11, 0x7d, 0xb5, 0x34, 0x55, 0xb7, 0x0f, 0x76, 0xed, 0x6c, 0x37, 0x30, 0xdb, 0xee,
	0x12, 0xea, 0xd9, 0x21, 0x42, 0xda, 0xf6, 0x93, 0xa5, 0x1d, 0x6d, 0xb4, 0xa5, 0x71, 0xee, 0x2a,
	0xec, 0x5f, 0xbf, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x37, 0x71, 0xa9, 0xe4, 0x92, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoolServiceClient interface {
	CountPools(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountPoolsResponse, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error)
	GetPoolAddresses(ctx context.Context, in *GetPoolAddressesRequest, opts ...grpc.CallOption) (*GetPoolAddressesResponse, error)
	GetPoolCoinbaseTags(ctx context.Context, in *GetPoolCoinbaseTagsRequest, opts ...grpc.CallOption) (*GetPoolCoinbaseTagsResponse, error)
	AddPoolCoinbaseAddress(ctx context.Context, in *AddPoolCoinbaseAddressRequest, opts ...grpc.CallOption) (*AddPoolCoinbaseAddressResponse, error)
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
}

type poolServiceClient struct {
	cc *grpc.ClientConn
}

func NewPoolServiceClient(cc *grpc.ClientConn) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) CountPools(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountPoolsResponse, error) {
	out := new(CountPoolsResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/CountPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error) {
	out := new(GetPoolResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/GetPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetPoolAddresses(ctx context.Context, in *GetPoolAddressesRequest, opts ...grpc.CallOption) (*GetPoolAddressesResponse, error) {
	out := new(GetPoolAddressesResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/GetPoolAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) GetPoolCoinbaseTags(ctx context.Context, in *GetPoolCoinbaseTagsRequest, opts ...grpc.CallOption) (*GetPoolCoinbaseTagsResponse, error) {
	out := new(GetPoolCoinbaseTagsResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/GetPoolCoinbaseTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) AddPoolCoinbaseAddress(ctx context.Context, in *AddPoolCoinbaseAddressRequest, opts ...grpc.CallOption) (*AddPoolCoinbaseAddressResponse, error) {
	out := new(AddPoolCoinbaseAddressResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/AddPoolCoinbaseAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, "/basedata.PoolService/ListPools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
type PoolServiceServer interface {
	CountPools(context.Context, *empty.Empty) (*CountPoolsResponse, error)
	GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error)
	GetPoolAddresses(context.Context, *GetPoolAddressesRequest) (*GetPoolAddressesResponse, error)
	GetPoolCoinbaseTags(context.Context, *GetPoolCoinbaseTagsRequest) (*GetPoolCoinbaseTagsResponse, error)
	AddPoolCoinbaseAddress(context.Context, *AddPoolCoinbaseAddressRequest) (*AddPoolCoinbaseAddressResponse, error)
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
}

// UnimplementedPoolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPoolServiceServer struct {
}

func (*UnimplementedPoolServiceServer) CountPools(ctx context.Context, req *empty.Empty) (*CountPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountPools not implemented")
}
func (*UnimplementedPoolServiceServer) GetPool(ctx context.Context, req *GetPoolRequest) (*GetPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPool not implemented")
}
func (*UnimplementedPoolServiceServer) GetPoolAddresses(ctx context.Context, req *GetPoolAddressesRequest) (*GetPoolAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolAddresses not implemented")
}
func (*UnimplementedPoolServiceServer) GetPoolCoinbaseTags(ctx context.Context, req *GetPoolCoinbaseTagsRequest) (*GetPoolCoinbaseTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolCoinbaseTags not implemented")
}
func (*UnimplementedPoolServiceServer) AddPoolCoinbaseAddress(ctx context.Context, req *AddPoolCoinbaseAddressRequest) (*AddPoolCoinbaseAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPoolCoinbaseAddress not implemented")
}
func (*UnimplementedPoolServiceServer) ListPools(ctx context.Context, req *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPools not implemented")
}

func RegisterPoolServiceServer(s *grpc.Server, srv PoolServiceServer) {
	s.RegisterService(&_PoolService_serviceDesc, srv)
}

func _PoolService_CountPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).CountPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/CountPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).CountPools(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/GetPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetPoolAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetPoolAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/GetPoolAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetPoolAddresses(ctx, req.(*GetPoolAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_GetPoolCoinbaseTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolCoinbaseTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).GetPoolCoinbaseTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/GetPoolCoinbaseTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).GetPoolCoinbaseTags(ctx, req.(*GetPoolCoinbaseTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_AddPoolCoinbaseAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPoolCoinbaseAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).AddPoolCoinbaseAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/AddPoolCoinbaseAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).AddPoolCoinbaseAddress(ctx, req.(*AddPoolCoinbaseAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.PoolService/ListPools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basedata.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountPools",
			Handler:    _PoolService_CountPools_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _PoolService_GetPool_Handler,
		},
		{
			MethodName: "GetPoolAddresses",
			Handler:    _PoolService_GetPoolAddresses_Handler,
		},
		{
			MethodName: "GetPoolCoinbaseTags",
			Handler:    _PoolService_GetPoolCoinbaseTags_Handler,
		},
		{
			MethodName: "AddPoolCoinbaseAddress",
			Handler:    _PoolService_AddPoolCoinbaseAddress_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _PoolService_ListPools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pool.proto",
}
