// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pow_coin.proto

package basedata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pow_Coin struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EnName               string   `protobuf:"bytes,3,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	EnTag                string   `protobuf:"bytes,4,opt,name=en_tag,json=enTag,proto3" json:"en_tag,omitempty"`
	MaxSupply            float64  `protobuf:"fixed64,5,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	AlgorithmId          int32    `protobuf:"varint,6,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	BlockTime            string   `protobuf:"bytes,7,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	WebsiteUrl           string   `protobuf:"bytes,8,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	GithubUrl            string   `protobuf:"bytes,9,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
	ReleaseDate          string   `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Icon                 string   `protobuf:"bytes,11,opt,name=icon,proto3" json:"icon,omitempty"`
	Intro                string   `protobuf:"bytes,12,opt,name=intro,proto3" json:"intro,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	ListOrder            int32    `protobuf:"varint,14,opt,name=list_order,json=listOrder,proto3" json:"list_order,omitempty"`
	CreatedAtTs          int32    `protobuf:"varint,15,opt,name=created_at_ts,json=createdAtTs,proto3" json:"created_at_ts,omitempty"`
	UpdatedAtTs          int32    `protobuf:"varint,16,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pow_Coin) Reset()         { *m = Pow_Coin{} }
func (m *Pow_Coin) String() string { return proto.CompactTextString(m) }
func (*Pow_Coin) ProtoMessage()    {}
func (*Pow_Coin) Descriptor() ([]byte, []int) {
	return fileDescriptor_04940dfa92f54e82, []int{0}
}

func (m *Pow_Coin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pow_Coin.Unmarshal(m, b)
}
func (m *Pow_Coin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pow_Coin.Marshal(b, m, deterministic)
}
func (m *Pow_Coin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pow_Coin.Merge(m, src)
}
func (m *Pow_Coin) XXX_Size() int {
	return xxx_messageInfo_Pow_Coin.Size(m)
}
func (m *Pow_Coin) XXX_DiscardUnknown() {
	xxx_messageInfo_Pow_Coin.DiscardUnknown(m)
}

var xxx_messageInfo_Pow_Coin proto.InternalMessageInfo

func (m *Pow_Coin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pow_Coin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pow_Coin) GetEnName() string {
	if m != nil {
		return m.EnName
	}
	return ""
}

func (m *Pow_Coin) GetEnTag() string {
	if m != nil {
		return m.EnTag
	}
	return ""
}

func (m *Pow_Coin) GetMaxSupply() float64 {
	if m != nil {
		return m.MaxSupply
	}
	return 0
}

func (m *Pow_Coin) GetAlgorithmId() int32 {
	if m != nil {
		return m.AlgorithmId
	}
	return 0
}

func (m *Pow_Coin) GetBlockTime() string {
	if m != nil {
		return m.BlockTime
	}
	return ""
}

func (m *Pow_Coin) GetWebsiteUrl() string {
	if m != nil {
		return m.WebsiteUrl
	}
	return ""
}

func (m *Pow_Coin) GetGithubUrl() string {
	if m != nil {
		return m.GithubUrl
	}
	return ""
}

func (m *Pow_Coin) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *Pow_Coin) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Pow_Coin) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *Pow_Coin) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Pow_Coin) GetListOrder() int32 {
	if m != nil {
		return m.ListOrder
	}
	return 0
}

func (m *Pow_Coin) GetCreatedAtTs() int32 {
	if m != nil {
		return m.CreatedAtTs
	}
	return 0
}

func (m *Pow_Coin) GetUpdatedAtTs() int32 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *Pow_Coin) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Pow_Coin) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CountPowCoinsResponse struct {
	Total                int32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountPowCoinsResponse) Reset()         { *m = CountPowCoinsResponse{} }
func (m *CountPowCoinsResponse) String() string { return proto.CompactTextString(m) }
func (*CountPowCoinsResponse) ProtoMessage()    {}
func (*CountPowCoinsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04940dfa92f54e82, []int{1}
}

func (m *CountPowCoinsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPowCoinsResponse.Unmarshal(m, b)
}
func (m *CountPowCoinsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPowCoinsResponse.Marshal(b, m, deterministic)
}
func (m *CountPowCoinsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPowCoinsResponse.Merge(m, src)
}
func (m *CountPowCoinsResponse) XXX_Size() int {
	return xxx_messageInfo_CountPowCoinsResponse.Size(m)
}
func (m *CountPowCoinsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPowCoinsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountPowCoinsResponse proto.InternalMessageInfo

func (m *CountPowCoinsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetPowCoinRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPowCoinRequest) Reset()         { *m = GetPowCoinRequest{} }
func (m *GetPowCoinRequest) String() string { return proto.CompactTextString(m) }
func (*GetPowCoinRequest) ProtoMessage()    {}
func (*GetPowCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04940dfa92f54e82, []int{2}
}

func (m *GetPowCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPowCoinRequest.Unmarshal(m, b)
}
func (m *GetPowCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPowCoinRequest.Marshal(b, m, deterministic)
}
func (m *GetPowCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPowCoinRequest.Merge(m, src)
}
func (m *GetPowCoinRequest) XXX_Size() int {
	return xxx_messageInfo_GetPowCoinRequest.Size(m)
}
func (m *GetPowCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPowCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPowCoinRequest proto.InternalMessageInfo

func (m *GetPowCoinRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPowCoinResponse struct {
	Coin                 *Pow_Coin `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPowCoinResponse) Reset()         { *m = GetPowCoinResponse{} }
func (m *GetPowCoinResponse) String() string { return proto.CompactTextString(m) }
func (*GetPowCoinResponse) ProtoMessage()    {}
func (*GetPowCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04940dfa92f54e82, []int{3}
}

func (m *GetPowCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPowCoinResponse.Unmarshal(m, b)
}
func (m *GetPowCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPowCoinResponse.Marshal(b, m, deterministic)
}
func (m *GetPowCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPowCoinResponse.Merge(m, src)
}
func (m *GetPowCoinResponse) XXX_Size() int {
	return xxx_messageInfo_GetPowCoinResponse.Size(m)
}
func (m *GetPowCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPowCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPowCoinResponse proto.InternalMessageInfo

func (m *GetPowCoinResponse) GetCoin() *Pow_Coin {
	if m != nil {
		return m.Coin
	}
	return nil
}

func init() {
	proto.RegisterType((*Pow_Coin)(nil), "basedata.Pow_Coin")
	proto.RegisterType((*CountPowCoinsResponse)(nil), "basedata.CountPowCoinsResponse")
	proto.RegisterType((*GetPowCoinRequest)(nil), "basedata.GetPowCoinRequest")
	proto.RegisterType((*GetPowCoinResponse)(nil), "basedata.GetPowCoinResponse")
}

func init() { proto.RegisterFile("pow_coin.proto", fileDescriptor_04940dfa92f54e82) }

var fileDescriptor_04940dfa92f54e82 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xc9, 0x68, 0xbb, 0xf5, 0xf6, 0x0f, 0xcc, 0x62, 0xc3, 0xea, 0x98, 0xd6, 0x05, 0x09,
	0xf5, 0x85, 0x4c, 0x1a, 0xaf, 0xbc, 0xa0, 0x81, 0xd0, 0x78, 0x60, 0x55, 0x56, 0xc4, 0xa3, 0xe5,
	0x34, 0x97, 0xcc, 0x22, 0x89, 0x43, 0x7c, 0x43, 0xb7, 0x8f, 0xc0, 0x27, 0xe1, 0x6b, 0x22, 0xdb,
	0x69, 0x3b, 0x60, 0x6f, 0xf1, 0xef, 0x9c, 0x7b, 0xe2, 0x6b, 0x1d, 0x18, 0x57, 0x7a, 0x25, 0x96,
	0x5a, 0x95, 0x51, 0x55, 0x6b, 0xd2, 0x6c, 0x2f, 0x91, 0x06, 0x53, 0x49, 0x72, 0x72, 0x94, 0x69,
	0x9d, 0xe5, 0x78, 0xe6, 0x78, 0xd2, 0x7c, 0x3b, 0xc3, 0xa2, 0xa2, 0x3b, 0x6f, 0x0b, 0x7f, 0x75,
	0x60, 0x6f, 0xae, 0x57, 0xe2, 0x42, 0xab, 0x92, 0x8d, 0x61, 0x47, 0xa5, 0x3c, 0x98, 0x06, 0xb3,
	0x6e, 0xbc, 0xa3, 0x52, 0xc6, 0xa0, 0x53, 0xca, 0x02, 0xf9, 0xce, 0x34, 0x98, 0xf5, 0x63, 0xf7,
	0xcd, 0x9e, 0xc3, 0x2e, 0x96, 0xc2, 0xe1, 0xc7, 0x0e, 0xf7, 0xb0, 0xfc, 0x6c, 0x85, 0x03, 0xe8,
	0x61, 0x29, 0x48, 0x66, 0xbc, 0xe3, 0x78, 0x17, 0xcb, 0x85, 0xcc, 0xd8, 0x31, 0x40, 0x21, 0x6f,
	0x85, 0x69, 0xaa, 0x2a, 0xbf, 0xe3, 0xdd, 0x69, 0x30, 0x0b, 0xe2, 0x7e, 0x21, 0x6f, 0xaf, 0x1d,
	0x60, 0xa7, 0x30, 0x94, 0x79, 0xa6, 0x6b, 0x45, 0x37, 0x85, 0x50, 0x29, 0xef, 0xb9, 0x9f, 0x0f,
	0x36, 0xec, 0x32, 0xb5, 0x09, 0x49, 0xae, 0x97, 0xdf, 0x05, 0xa9, 0x02, 0xf9, 0xae, 0x0b, 0xef,
	0x3b, 0xb2, 0x50, 0x05, 0xb2, 0x13, 0x18, 0xac, 0x30, 0x31, 0x8a, 0x50, 0x34, 0x75, 0xce, 0xf7,
	0x9c, 0x0e, 0x2d, 0xfa, 0x52, 0xe7, 0x76, 0x3e, 0x53, 0x74, 0xd3, 0x24, 0x4e, 0xef, 0xfb, 0x79,
	0x4f, 0xac, 0x7c, 0x0a, 0xc3, 0x1a, 0x73, 0x94, 0x06, 0x45, 0x2a, 0x09, 0x39, 0x38, 0xc3, 0xa0,
	0x65, 0xef, 0x25, 0xa1, 0x7d, 0x07, 0xb5, 0xd4, 0x25, 0x1f, 0xf8, 0x77, 0xb0, 0xdf, 0xec, 0x19,
	0x74, 0x55, 0x49, 0xb5, 0xe6, 0x43, 0xbf, 0xad, 0x3b, 0xb0, 0x43, 0xe8, 0x19, 0x92, 0xd4, 0x18,
	0x3e, 0x72, 0x8b, 0xb4, 0x27, 0x7b, 0x87, 0x5c, 0x19, 0x12, 0xba, 0x4e, 0xb1, 0xe6, 0x63, 0xa7,
	0xf5, 0x2d, 0xb9, 0xb2, 0x80, 0x85, 0x30, 0x5a, 0xd6, 0x28, 0x09, 0x53, 0x21, 0x49, 0x90, 0xe1,
	0x4f, 0xfc, 0x33, 0xb4, 0xf0, 0x1d, 0x2d, 0x8c, 0xf5, 0x34, 0x55, 0x7a, 0xcf, 0xf3, 0xd4, 0x7b,
	0x5a, 0xe8, 0x3c, 0xc7, 0x00, 0xdb, 0x1c, 0xbe, 0xef, 0x57, 0xdd, 0x84, 0x58, 0x79, 0x1b, 0xc1,
	0x99, 0x97, 0x37, 0xf3, 0xe1, 0x6b, 0x38, 0xb8, 0xd0, 0x4d, 0x49, 0x73, 0xbd, 0xb2, 0x75, 0x30,
	0x31, 0x9a, 0x4a, 0x97, 0x06, 0xed, 0xae, 0xa4, 0x49, 0xe6, 0x6d, 0x35, 0xfc, 0x21, 0x7c, 0x09,
	0xfb, 0x1f, 0x71, 0x6d, 0x8e, 0xf1, 0x47, 0x83, 0x86, 0xfe, 0xad, 0x50, 0xf8, 0x16, 0xd8, 0x7d,
	0x53, 0x1b, 0xf8, 0x0a, 0x3a, 0xb6, 0xaa, 0xce, 0x37, 0x38, 0x67, 0xd1, 0xba, 0xab, 0xd1, 0xba,
	0x8a, 0xb1, 0xd3, 0xcf, 0x7f, 0x07, 0x30, 0x9e, 0x5f, 0x7d, 0xb5, 0xe4, 0x1a, 0xeb, 0x9f, 0x6a,
	0x89, 0xec, 0x13, 0x8c, 0xfe, 0xba, 0x24, 0x3b, 0x8c, 0x7c, 0xbf, 0xa3, 0x75, 0xbf, 0xa3, 0x0f,
	0xb6, 0xdf, 0x93, 0x93, 0x6d, 0xea, 0x83, 0x5b, 0x85, 0x8f, 0xd8, 0x25, 0xc0, 0xf6, 0x72, 0xec,
	0x68, 0x3b, 0xf0, 0xdf, 0x5e, 0x93, 0x17, 0x0f, 0x8b, 0xeb, 0xa8, 0xa4, 0xe7, 0xfe, 0xfe, 0xe6,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd7, 0xf7, 0x85, 0x87, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// POWCoinServiceClient is the client API for POWCoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type POWCoinServiceClient interface {
	CountPowCoins(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountPowCoinsResponse, error)
	GetPowCoin(ctx context.Context, in *GetPowCoinRequest, opts ...grpc.CallOption) (*GetPowCoinResponse, error)
}

type pOWCoinServiceClient struct {
	cc *grpc.ClientConn
}

func NewPOWCoinServiceClient(cc *grpc.ClientConn) POWCoinServiceClient {
	return &pOWCoinServiceClient{cc}
}

func (c *pOWCoinServiceClient) CountPowCoins(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CountPowCoinsResponse, error) {
	out := new(CountPowCoinsResponse)
	err := c.cc.Invoke(ctx, "/basedata.POWCoinService/CountPowCoins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pOWCoinServiceClient) GetPowCoin(ctx context.Context, in *GetPowCoinRequest, opts ...grpc.CallOption) (*GetPowCoinResponse, error) {
	out := new(GetPowCoinResponse)
	err := c.cc.Invoke(ctx, "/basedata.POWCoinService/GetPowCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// POWCoinServiceServer is the server API for POWCoinService service.
type POWCoinServiceServer interface {
	CountPowCoins(context.Context, *empty.Empty) (*CountPowCoinsResponse, error)
	GetPowCoin(context.Context, *GetPowCoinRequest) (*GetPowCoinResponse, error)
}

// UnimplementedPOWCoinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPOWCoinServiceServer struct {
}

func (*UnimplementedPOWCoinServiceServer) CountPowCoins(ctx context.Context, req *empty.Empty) (*CountPowCoinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountPowCoins not implemented")
}
func (*UnimplementedPOWCoinServiceServer) GetPowCoin(ctx context.Context, req *GetPowCoinRequest) (*GetPowCoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPowCoin not implemented")
}

func RegisterPOWCoinServiceServer(s *grpc.Server, srv POWCoinServiceServer) {
	s.RegisterService(&_POWCoinService_serviceDesc, srv)
}

func _POWCoinService_CountPowCoins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POWCoinServiceServer).CountPowCoins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.POWCoinService/CountPowCoins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POWCoinServiceServer).CountPowCoins(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _POWCoinService_GetPowCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPowCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(POWCoinServiceServer).GetPowCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basedata.POWCoinService/GetPowCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(POWCoinServiceServer).GetPowCoin(ctx, req.(*GetPowCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _POWCoinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basedata.POWCoinService",
	HandlerType: (*POWCoinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountPowCoins",
			Handler:    _POWCoinService_CountPowCoins_Handler,
		},
		{
			MethodName: "GetPowCoin",
			Handler:    _POWCoinService_GetPowCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pow_coin.proto",
}
