// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coinmarkercap.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Quote struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EnTag                string   `protobuf:"bytes,2,opt,name=en_tag,json=enTag,proto3" json:"en_tag,omitempty"`
	CirculatingSupply    float64  `protobuf:"fixed64,3,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	NumMarkerPairs       int32    `protobuf:"varint,4,opt,name=num_marker_pairs,json=numMarkerPairs,proto3" json:"num_marker_pairs,omitempty"`
	CmcRank              int32    `protobuf:"varint,5,opt,name=cmc_rank,json=cmcRank,proto3" json:"cmc_rank,omitempty"`
	EurPrice             float64  `protobuf:"fixed64,6,opt,name=eur_price,json=eurPrice,proto3" json:"eur_price,omitempty"`
	Volume_24H           float64  `protobuf:"fixed64,7,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	PercentChange_1H     float64  `protobuf:"fixed64,8,opt,name=percent_change_1h,json=percentChange1h,proto3" json:"percent_change_1h,omitempty"`
	PercentChange_24H    float64  `protobuf:"fixed64,9,opt,name=percent_change_24h,json=percentChange24h,proto3" json:"percent_change_24h,omitempty"`
	PercentChange_7D     float64  `protobuf:"fixed64,10,opt,name=percent_change_7d,json=percentChange7d,proto3" json:"percent_change_7d,omitempty"`
	MarketCap            float64  `protobuf:"fixed64,11,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	CratedAtTs           int64    `protobuf:"varint,12,opt,name=crated_at_ts,json=cratedAtTs,proto3" json:"crated_at_ts,omitempty"`
	UpdatedAtTs          int64    `protobuf:"varint,13,opt,name=updated_at_ts,json=updatedAtTs,proto3" json:"updated_at_ts,omitempty"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_85dcc4e28b504783, []int{0}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Quote) GetEnTag() string {
	if m != nil {
		return m.EnTag
	}
	return ""
}

func (m *Quote) GetCirculatingSupply() float64 {
	if m != nil {
		return m.CirculatingSupply
	}
	return 0
}

func (m *Quote) GetNumMarkerPairs() int32 {
	if m != nil {
		return m.NumMarkerPairs
	}
	return 0
}

func (m *Quote) GetCmcRank() int32 {
	if m != nil {
		return m.CmcRank
	}
	return 0
}

func (m *Quote) GetEurPrice() float64 {
	if m != nil {
		return m.EurPrice
	}
	return 0
}

func (m *Quote) GetVolume_24H() float64 {
	if m != nil {
		return m.Volume_24H
	}
	return 0
}

func (m *Quote) GetPercentChange_1H() float64 {
	if m != nil {
		return m.PercentChange_1H
	}
	return 0
}

func (m *Quote) GetPercentChange_24H() float64 {
	if m != nil {
		return m.PercentChange_24H
	}
	return 0
}

func (m *Quote) GetPercentChange_7D() float64 {
	if m != nil {
		return m.PercentChange_7D
	}
	return 0
}

func (m *Quote) GetMarketCap() float64 {
	if m != nil {
		return m.MarketCap
	}
	return 0
}

func (m *Quote) GetCratedAtTs() int64 {
	if m != nil {
		return m.CratedAtTs
	}
	return 0
}

func (m *Quote) GetUpdatedAtTs() int64 {
	if m != nil {
		return m.UpdatedAtTs
	}
	return 0
}

func (m *Quote) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Quote) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetQuoteRequest struct {
	EnTag                string   `protobuf:"bytes,1,opt,name=en_tag,json=enTag,proto3" json:"en_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteRequest) Reset()         { *m = GetQuoteRequest{} }
func (m *GetQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuoteRequest) ProtoMessage()    {}
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85dcc4e28b504783, []int{1}
}

func (m *GetQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteRequest.Unmarshal(m, b)
}
func (m *GetQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteRequest.Marshal(b, m, deterministic)
}
func (m *GetQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteRequest.Merge(m, src)
}
func (m *GetQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuoteRequest.Size(m)
}
func (m *GetQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteRequest proto.InternalMessageInfo

func (m *GetQuoteRequest) GetEnTag() string {
	if m != nil {
		return m.EnTag
	}
	return ""
}

type GetQuoteResponse struct {
	Quote                *Quote   `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteResponse) Reset()         { *m = GetQuoteResponse{} }
func (m *GetQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuoteResponse) ProtoMessage()    {}
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85dcc4e28b504783, []int{2}
}

func (m *GetQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteResponse.Unmarshal(m, b)
}
func (m *GetQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteResponse.Marshal(b, m, deterministic)
}
func (m *GetQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteResponse.Merge(m, src)
}
func (m *GetQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuoteResponse.Size(m)
}
func (m *GetQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteResponse proto.InternalMessageInfo

func (m *GetQuoteResponse) GetQuote() *Quote {
	if m != nil {
		return m.Quote
	}
	return nil
}

func init() {
	proto.RegisterType((*Quote)(nil), "agent.Quote")
	proto.RegisterType((*GetQuoteRequest)(nil), "agent.GetQuoteRequest")
	proto.RegisterType((*GetQuoteResponse)(nil), "agent.GetQuoteResponse")
}

func init() { proto.RegisterFile("coinmarkercap.proto", fileDescriptor_85dcc4e28b504783) }

var fileDescriptor_85dcc4e28b504783 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0xb7, 0x74, 0xcd, 0x6b, 0xd7, 0x76, 0x46, 0x03, 0x03, 0x9a, 0x14, 0xe5, 0x14,
	0x21, 0xa8, 0xb4, 0x32, 0xb1, 0x13, 0x87, 0xa9, 0x07, 0x4e, 0x93, 0x46, 0x36, 0x71, 0xb5, 0x8c,
	0xf3, 0x94, 0x58, 0x6d, 0x1c, 0xcf, 0xb1, 0x27, 0xf1, 0x09, 0xf8, 0xda, 0x28, 0x76, 0x60, 0x65,
	0xec, 0x98, 0xdf, 0xff, 0xe7, 0xf7, 0x5e, 0xec, 0x07, 0x2f, 0x45, 0x2b, 0x55, 0xc3, 0xcd, 0x16,
	0x8d, 0xe0, 0x7a, 0xa5, 0x4d, 0x6b, 0x5b, 0x12, 0xf3, 0x0a, 0x95, 0xcd, 0x7e, 0x1d, 0x42, 0xfc,
	0xcd, 0xb5, 0x16, 0xc9, 0x1c, 0x46, 0xb2, 0xa4, 0x51, 0x1a, 0xe5, 0x71, 0x31, 0x92, 0x25, 0x39,
	0x85, 0x31, 0x2a, 0x66, 0x79, 0x45, 0x47, 0x69, 0x94, 0x27, 0x45, 0x8c, 0xea, 0x8e, 0x57, 0xe4,
	0x23, 0x10, 0x21, 0x8d, 0x70, 0x3b, 0x6e, 0xa5, 0xaa, 0x58, 0xe7, 0xb4, 0xde, 0xfd, 0xa4, 0x07,
	0x69, 0x94, 0x47, 0xc5, 0xc9, 0x5e, 0x72, 0xeb, 0x03, 0x92, 0xc3, 0x52, 0xb9, 0x86, 0x85, 0xee,
	0x4c, 0x73, 0x69, 0x3a, 0x7a, 0xe8, 0x7b, 0xcc, 0x95, 0x6b, 0xae, 0x3d, 0xbe, 0xe9, 0x29, 0x79,
	0x03, 0x13, 0xd1, 0x08, 0x66, 0xb8, 0xda, 0xd2, 0xd8, 0x1b, 0x47, 0xa2, 0x11, 0x05, 0x57, 0x5b,
	0xf2, 0x0e, 0x12, 0x74, 0x86, 0x69, 0x23, 0x05, 0xd2, 0xb1, 0x6f, 0x35, 0x41, 0x67, 0x6e, 0xfa,
	0x6f, 0x72, 0x06, 0xf0, 0xd0, 0xee, 0x5c, 0x83, 0x6c, 0x7d, 0x51, 0xd3, 0x23, 0x9f, 0x26, 0x81,
	0xac, 0x2f, 0x6a, 0xf2, 0x1e, 0x4e, 0x34, 0x1a, 0x81, 0xca, 0x32, 0x51, 0x73, 0x55, 0x21, 0x3b,
	0xaf, 0xe9, 0xc4, 0x5b, 0x8b, 0x21, 0xd8, 0x78, 0x7e, 0x5e, 0x93, 0x0f, 0x40, 0x9e, 0xb8, 0x7d,
	0xc9, 0xc4, 0xcb, 0xcb, 0x7f, 0xe4, 0xe7, 0x2b, 0x5f, 0x96, 0x14, 0x9e, 0xa9, 0x7c, 0x59, 0xf6,
	0x43, 0xfa, 0x2b, 0xb0, 0x4c, 0x70, 0x4d, 0xa7, 0x61, 0xc8, 0x40, 0x36, 0x5c, 0x93, 0x14, 0x66,
	0xc2, 0x70, 0x8b, 0x25, 0xe3, 0x96, 0xd9, 0x8e, 0xce, 0xd2, 0x28, 0x3f, 0x28, 0x20, 0xb0, 0x2b,
	0x7b, 0xd7, 0x91, 0x0c, 0x8e, 0x9d, 0x2e, 0xf7, 0x94, 0x63, 0xaf, 0x4c, 0x07, 0xe8, 0x9d, 0x33,
	0x00, 0x61, 0x70, 0x70, 0xe8, 0xdc, 0xbf, 0x5a, 0x32, 0x90, 0x2b, 0xdb, 0xc7, 0x8f, 0x25, 0xe8,
	0x22, 0xc4, 0x7f, 0xcf, 0x67, 0x39, 0x2c, 0xbe, 0xa2, 0xf5, 0xbb, 0x50, 0xe0, 0xbd, 0xc3, 0xce,
	0xee, 0xad, 0x40, 0xb4, 0xb7, 0x02, 0xd9, 0x67, 0x58, 0x3e, 0x9a, 0x9d, 0x6e, 0x55, 0x87, 0x24,
	0x83, 0xf8, 0xbe, 0x07, 0xde, 0x9c, 0xae, 0x67, 0x2b, 0xbf, 0x5e, 0xab, 0x20, 0x85, 0x68, 0xfd,
	0x1d, 0x4e, 0x37, 0xad, 0x54, 0xd7, 0xdc, 0xf0, 0xf0, 0xdf, 0xb7, 0x68, 0x1e, 0xfa, 0x27, 0xfc,
	0x02, 0x93, 0x3f, 0x05, 0xc9, 0xab, 0xe1, 0xe4, 0x93, 0x59, 0xde, 0xbe, 0xfe, 0x8f, 0x87, 0xce,
	0xd9, 0x8b, 0x1f, 0x63, 0xbf, 0xd1, 0x9f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x41, 0x13,
	0x02, 0xe8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoinMaraketCapServiceClient is the client API for CoinMaraketCapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoinMaraketCapServiceClient interface {
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
}

type coinMaraketCapServiceClient struct {
	cc *grpc.ClientConn
}

func NewCoinMaraketCapServiceClient(cc *grpc.ClientConn) CoinMaraketCapServiceClient {
	return &coinMaraketCapServiceClient{cc}
}

func (c *coinMaraketCapServiceClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, "/agent.CoinMaraketCapService/GetQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinMaraketCapServiceServer is the server API for CoinMaraketCapService service.
type CoinMaraketCapServiceServer interface {
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
}

// UnimplementedCoinMaraketCapServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCoinMaraketCapServiceServer struct {
}

func (*UnimplementedCoinMaraketCapServiceServer) GetQuote(ctx context.Context, req *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}

func RegisterCoinMaraketCapServiceServer(s *grpc.Server, srv CoinMaraketCapServiceServer) {
	s.RegisterService(&_CoinMaraketCapService_serviceDesc, srv)
}

func _CoinMaraketCapService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinMaraketCapServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.CoinMaraketCapService/GetQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinMaraketCapServiceServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoinMaraketCapService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.CoinMaraketCapService",
	HandlerType: (*CoinMaraketCapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _CoinMaraketCapService_GetQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coinmarkercap.proto",
}
