// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block_stats.proto

package stats

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockStats struct {
	Id                          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CoinId                      int32    `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	LatestHeight                int32    `protobuf:"varint,3,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	LatestDifficulty            float64  `protobuf:"fixed64,4,opt,name=latest_difficulty,json=latestDifficulty,proto3" json:"latest_difficulty,omitempty"`
	NetHash                     string   `protobuf:"bytes,5,opt,name=net_hash,json=netHash,proto3" json:"net_hash,omitempty"`
	NetHashOneDay               string   `protobuf:"bytes,6,opt,name=net_hash_one_day,json=netHashOneDay,proto3" json:"net_hash_one_day,omitempty"`
	NetHashHalfWeek             string   `protobuf:"bytes,7,opt,name=net_hash_half_week,json=netHashHalfWeek,proto3" json:"net_hash_half_week,omitempty"`
	NetHashOneWeek              string   `protobuf:"bytes,8,opt,name=net_hash_one_week,json=netHashOneWeek,proto3" json:"net_hash_one_week,omitempty"`
	NetHashTwoWeek              string   `protobuf:"bytes,9,opt,name=net_hash_two_week,json=netHashTwoWeek,proto3" json:"net_hash_two_week,omitempty"`
	RewardPerUnit               float64  `protobuf:"fixed64,10,opt,name=reward_per_unit,json=rewardPerUnit,proto3" json:"reward_per_unit,omitempty"`
	PreviousDifficulty          float64  `protobuf:"fixed64,11,opt,name=previous_difficulty,json=previousDifficulty,proto3" json:"previous_difficulty,omitempty"`
	LatestDifficultyChange      string   `protobuf:"bytes,12,opt,name=latest_difficulty_change,json=latestDifficultyChange,proto3" json:"latest_difficulty_change,omitempty"`
	LatestDifficultyChangeTs    int32    `protobuf:"varint,13,opt,name=latest_difficulty_change_ts,json=latestDifficultyChangeTs,proto3" json:"latest_difficulty_change_ts,omitempty"`
	NextDifficultyChangeSeconds int32    `protobuf:"varint,14,opt,name=next_difficulty_change_seconds,json=nextDifficultyChangeSeconds,proto3" json:"next_difficulty_change_seconds,omitempty"`
	UpdatedTs                   int32    `protobuf:"varint,15,opt,name=updated_ts,json=updatedTs,proto3" json:"updated_ts,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *BlockStats) Reset()         { *m = BlockStats{} }
func (m *BlockStats) String() string { return proto.CompactTextString(m) }
func (*BlockStats) ProtoMessage()    {}
func (*BlockStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e64c6f7ef17d710, []int{0}
}

func (m *BlockStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStats.Unmarshal(m, b)
}
func (m *BlockStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStats.Marshal(b, m, deterministic)
}
func (m *BlockStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStats.Merge(m, src)
}
func (m *BlockStats) XXX_Size() int {
	return xxx_messageInfo_BlockStats.Size(m)
}
func (m *BlockStats) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStats.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStats proto.InternalMessageInfo

func (m *BlockStats) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlockStats) GetCoinId() int32 {
	if m != nil {
		return m.CoinId
	}
	return 0
}

func (m *BlockStats) GetLatestHeight() int32 {
	if m != nil {
		return m.LatestHeight
	}
	return 0
}

func (m *BlockStats) GetLatestDifficulty() float64 {
	if m != nil {
		return m.LatestDifficulty
	}
	return 0
}

func (m *BlockStats) GetNetHash() string {
	if m != nil {
		return m.NetHash
	}
	return ""
}

func (m *BlockStats) GetNetHashOneDay() string {
	if m != nil {
		return m.NetHashOneDay
	}
	return ""
}

func (m *BlockStats) GetNetHashHalfWeek() string {
	if m != nil {
		return m.NetHashHalfWeek
	}
	return ""
}

func (m *BlockStats) GetNetHashOneWeek() string {
	if m != nil {
		return m.NetHashOneWeek
	}
	return ""
}

func (m *BlockStats) GetNetHashTwoWeek() string {
	if m != nil {
		return m.NetHashTwoWeek
	}
	return ""
}

func (m *BlockStats) GetRewardPerUnit() float64 {
	if m != nil {
		return m.RewardPerUnit
	}
	return 0
}

func (m *BlockStats) GetPreviousDifficulty() float64 {
	if m != nil {
		return m.PreviousDifficulty
	}
	return 0
}

func (m *BlockStats) GetLatestDifficultyChange() string {
	if m != nil {
		return m.LatestDifficultyChange
	}
	return ""
}

func (m *BlockStats) GetLatestDifficultyChangeTs() int32 {
	if m != nil {
		return m.LatestDifficultyChangeTs
	}
	return 0
}

func (m *BlockStats) GetNextDifficultyChangeSeconds() int32 {
	if m != nil {
		return m.NextDifficultyChangeSeconds
	}
	return 0
}

func (m *BlockStats) GetUpdatedTs() int32 {
	if m != nil {
		return m.UpdatedTs
	}
	return 0
}

type GetBlockStatsRequest struct {
	CoinId               int32    `protobuf:"varint,1,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockStatsRequest) Reset()         { *m = GetBlockStatsRequest{} }
func (m *GetBlockStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockStatsRequest) ProtoMessage()    {}
func (*GetBlockStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e64c6f7ef17d710, []int{1}
}

func (m *GetBlockStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockStatsRequest.Unmarshal(m, b)
}
func (m *GetBlockStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockStatsRequest.Merge(m, src)
}
func (m *GetBlockStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockStatsRequest.Size(m)
}
func (m *GetBlockStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockStatsRequest proto.InternalMessageInfo

func (m *GetBlockStatsRequest) GetCoinId() int32 {
	if m != nil {
		return m.CoinId
	}
	return 0
}

type GetBlockStatsResponse struct {
	Stats                *BlockStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBlockStatsResponse) Reset()         { *m = GetBlockStatsResponse{} }
func (m *GetBlockStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockStatsResponse) ProtoMessage()    {}
func (*GetBlockStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e64c6f7ef17d710, []int{2}
}

func (m *GetBlockStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockStatsResponse.Unmarshal(m, b)
}
func (m *GetBlockStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockStatsResponse.Merge(m, src)
}
func (m *GetBlockStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockStatsResponse.Size(m)
}
func (m *GetBlockStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockStatsResponse proto.InternalMessageInfo

func (m *GetBlockStatsResponse) GetStats() *BlockStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockStats)(nil), "stats.BlockStats")
	proto.RegisterType((*GetBlockStatsRequest)(nil), "stats.GetBlockStatsRequest")
	proto.RegisterType((*GetBlockStatsResponse)(nil), "stats.GetBlockStatsResponse")
}

func init() { proto.RegisterFile("block_stats.proto", fileDescriptor_1e64c6f7ef17d710) }

var fileDescriptor_1e64c6f7ef17d710 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0xa1, 0xed, 0x7a, 0x5b, 0xda, 0xc5, 0xfc, 0x32, 0x14, 0x50, 0x55, 0x24, 0x56,
	0x34, 0x69, 0x93, 0xc6, 0x0b, 0x2f, 0x48, 0x88, 0x4d, 0xa2, 0x48, 0x48, 0xa0, 0xb6, 0x88, 0x47,
	0xcb, 0x8b, 0xaf, 0x8b, 0xd5, 0xc8, 0x0e, 0xb1, 0xb3, 0xd2, 0x77, 0xfe, 0x70, 0x14, 0x3b, 0x5b,
	0xd3, 0xae, 0x7b, 0xbc, 0xef, 0xf7, 0xf3, 0xbd, 0x5c, 0x2e, 0x17, 0x88, 0x2e, 0x53, 0x1d, 0x2f,
	0x98, 0xb1, 0xdc, 0x9a, 0x93, 0x2c, 0xd7, 0x56, 0x93, 0xa6, 0x2b, 0x86, 0xff, 0x9a, 0x00, 0x5f,
	0x4a, 0x73, 0x5a, 0x96, 0xa4, 0x0b, 0x0d, 0x29, 0x68, 0x30, 0x08, 0x46, 0x9d, 0x49, 0x43, 0x0a,
	0xf2, 0x1c, 0xda, 0xb1, 0x96, 0x8a, 0x49, 0x41, 0x1b, 0x83, 0x60, 0xd4, 0x9c, 0xb4, 0xca, 0xf2,
	0x9b, 0x20, 0x6f, 0x21, 0x4c, 0xb9, 0x45, 0x63, 0x59, 0x82, 0xf2, 0x2a, 0xb1, 0xf4, 0xa1, 0xb3,
	0x0f, 0xbc, 0x38, 0x76, 0x1a, 0x39, 0x86, 0xa8, 0x82, 0x84, 0x9c, 0xcf, 0x65, 0x5c, 0xa4, 0x76,
	0x45, 0x1f, 0x0d, 0x82, 0x51, 0x30, 0x39, 0xf4, 0xc6, 0xc5, 0xad, 0x4e, 0x5e, 0xc0, 0x9e, 0x42,
	0xcb, 0x12, 0x6e, 0x12, 0xda, 0x74, 0x03, 0xb4, 0x15, 0xda, 0x31, 0x37, 0x09, 0x39, 0x82, 0xc3,
	0x1b, 0x8b, 0x69, 0x85, 0x4c, 0xf0, 0x15, 0x6d, 0x39, 0x24, 0xac, 0x90, 0x1f, 0x0a, 0x2f, 0xf8,
	0x8a, 0x1c, 0x03, 0xb9, 0x05, 0x13, 0x9e, 0xce, 0xd9, 0x12, 0x71, 0x41, 0xdb, 0x0e, 0xed, 0x55,
	0xe8, 0x98, 0xa7, 0xf3, 0xdf, 0x88, 0x0b, 0xf2, 0x1e, 0xa2, 0x8d, 0xae, 0x8e, 0xdd, 0x73, 0x6c,
	0x77, 0xdd, 0xf6, 0x0e, 0x6a, 0x97, 0xda, 0xa3, 0x9d, 0x0d, 0x74, 0xb6, 0xd4, 0x0e, 0x7d, 0x07,
	0xbd, 0x1c, 0x97, 0x3c, 0x17, 0x2c, 0xc3, 0x9c, 0x15, 0x4a, 0x5a, 0x0a, 0xee, 0x8d, 0x43, 0x2f,
	0xff, 0xc4, 0xfc, 0x97, 0x92, 0x96, 0x9c, 0xc2, 0xe3, 0x2c, 0xc7, 0x6b, 0xa9, 0x0b, 0x53, 0xdf,
	0xce, 0xbe, 0x63, 0xc9, 0x8d, 0x55, 0xdb, 0xcf, 0x47, 0xa0, 0x77, 0x96, 0xc9, 0xe2, 0x84, 0xab,
	0x2b, 0xa4, 0x07, 0x6e, 0x94, 0x67, 0xdb, 0x3b, 0x3d, 0x77, 0x2e, 0xf9, 0x04, 0xfd, 0xfb, 0x92,
	0xcc, 0x1a, 0x1a, 0xba, 0x2f, 0x47, 0x77, 0x87, 0x67, 0x86, 0x9c, 0xc3, 0x1b, 0x85, 0x7f, 0x77,
	0x85, 0x0d, 0xc6, 0x5a, 0x09, 0x43, 0xbb, 0xae, 0x43, 0xbf, 0xa4, 0xb6, 0xf3, 0x53, 0x8f, 0x90,
	0xd7, 0x00, 0x45, 0x26, 0xb8, 0x45, 0x51, 0x3e, 0xb2, 0xe7, 0x02, 0x9d, 0x4a, 0x99, 0x99, 0xe1,
	0x29, 0x3c, 0xf9, 0x8a, 0x76, 0x7d, 0x88, 0x13, 0xfc, 0x53, 0xa0, 0xb1, 0xf5, 0xfb, 0x0b, 0xea,
	0xf7, 0x37, 0xfc, 0x0c, 0x4f, 0xb7, 0x02, 0x26, 0xd3, 0xca, 0x20, 0x39, 0x02, 0x7f, 0xd9, 0x8e,
	0xdf, 0x3f, 0x8b, 0x4e, 0xfc, 0xd1, 0xd7, 0x48, 0xef, 0x9f, 0x71, 0x88, 0xd6, 0xe2, 0x14, 0xf3,
	0x6b, 0x19, 0x23, 0xf9, 0x0e, 0xe1, 0x46, 0x5b, 0xd2, 0xaf, 0xf2, 0xbb, 0xa6, 0x7b, 0xf9, 0x6a,
	0xb7, 0xe9, 0x27, 0x19, 0x3e, 0xb8, 0x6c, 0xb9, 0x5f, 0xed, 0xc3, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb6, 0x1f, 0x1a, 0x68, 0x7f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockStatsServiceClient is the client API for BlockStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockStatsServiceClient interface {
	GetBlockStats(ctx context.Context, in *GetBlockStatsRequest, opts ...grpc.CallOption) (*GetBlockStatsResponse, error)
}

type blockStatsServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlockStatsServiceClient(cc *grpc.ClientConn) BlockStatsServiceClient {
	return &blockStatsServiceClient{cc}
}

func (c *blockStatsServiceClient) GetBlockStats(ctx context.Context, in *GetBlockStatsRequest, opts ...grpc.CallOption) (*GetBlockStatsResponse, error) {
	out := new(GetBlockStatsResponse)
	err := c.cc.Invoke(ctx, "/stats.BlockStatsService/GetBlockStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockStatsServiceServer is the server API for BlockStatsService service.
type BlockStatsServiceServer interface {
	GetBlockStats(context.Context, *GetBlockStatsRequest) (*GetBlockStatsResponse, error)
}

// UnimplementedBlockStatsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockStatsServiceServer struct {
}

func (*UnimplementedBlockStatsServiceServer) GetBlockStats(ctx context.Context, req *GetBlockStatsRequest) (*GetBlockStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockStats not implemented")
}

func RegisterBlockStatsServiceServer(s *grpc.Server, srv BlockStatsServiceServer) {
	s.RegisterService(&_BlockStatsService_serviceDesc, srv)
}

func _BlockStatsService_GetBlockStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockStatsServiceServer).GetBlockStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.BlockStatsService/GetBlockStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockStatsServiceServer).GetBlockStats(ctx, req.(*GetBlockStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockStatsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stats.BlockStatsService",
	HandlerType: (*BlockStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockStats",
			Handler:    _BlockStatsService_GetBlockStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block_stats.proto",
}
